# Violation: disable determinism
violations:
  enabled: true
  active:
    - nondeterminism
  
  nondeterminism:
    seed_randomization: true
    disable_deterministic: true
    use_nondeterministic_algorithms: true
